# Generated by Django 5.0.4 on 2024-04-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_isbn_book_isbn_book_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_quantity',
        ),
    ]
