# Generated by Django 5.0.4 on 2024-04-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquantity',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author'),
        ),
    ]
